// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmLwKmtI3ADWiHj0_-ykUHAc2_LFpqC2M',
    appId: '1:785743227302:web:eb54ec3c03cc582a810767',
    messagingSenderId: '785743227302',
    projectId: 'pantau-d0ef6',
    authDomain: 'pantau-d0ef6.firebaseapp.com',
    databaseURL: 'https://pantau-d0ef6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pantau-d0ef6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb4-9Z7sc3LEwNNMsZ9THWq_hFkteCkaQ',
    appId: '1:785743227302:android:e04269581e0a0ce6810767',
    messagingSenderId: '785743227302',
    projectId: 'pantau-d0ef6',
    databaseURL: 'https://pantau-d0ef6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pantau-d0ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5oTKRVWUW0DV_8XM_XXGBAgaG7--vZVo',
    appId: '1:785743227302:ios:abcadd99617171d6810767',
    messagingSenderId: '785743227302',
    projectId: 'pantau-d0ef6',
    databaseURL: 'https://pantau-d0ef6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pantau-d0ef6.appspot.com',
    iosClientId: '785743227302-ag7l0lfm68df8f1dvaat1hrvf6r3opu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5oTKRVWUW0DV_8XM_XXGBAgaG7--vZVo',
    appId: '1:785743227302:ios:abcadd99617171d6810767',
    messagingSenderId: '785743227302',
    projectId: 'pantau-d0ef6',
    databaseURL: 'https://pantau-d0ef6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pantau-d0ef6.appspot.com',
    iosClientId: '785743227302-ag7l0lfm68df8f1dvaat1hrvf6r3opu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantau',
  );
}
